### ISSUE TITLE
Question: serverless dynamo local data

### ISSUE THREAD

**Issue by eduardoamills** [anishkny/realworld-dynamodb-lambda#65]
Hi

I am new with dynamo, when I restart this project the previous data are lost...there are some way to keep my local data during development?? In building a several tables, is realy hard to fill al tables when the services is restarted.
I hope that you can help me.

regards

PS: sorry for ignorance if the answer is obvious, it is overwhelming to absorb so much knowledge so fast

**Comment by anishkny** [comment]
@eduardoamills you would need to use `sls dynamodb migrate` and `sls dynamodb seed` to recreate the tables and data on DynamoDB local. See: https://github.com/99xt/serverless-dynamodb-local#migrations-sls-dynamodb-migrate

The way the tests are setup, they do not depend on any data being present in the local DynamoDB so migrate/seed is not required.
